brace_expansion: true

rules:
  - labels: [infrastructure]
    patterns: ['*|{tools,requirements,.github}/**|!README.md']

  - labels: [source]
    patterns: ['soupsieve/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [docs]
    patterns: ['docs/**|README.md']

  - labels: [API]
    patterns: ['soupsieve/__init__.py']

  - labels: [css-parsing]
    patterns: ['soupsieve/css_parser.py']

  - labels: [css-matching]
    patterns: ['soupsieve/css_match.py']

  - labels: [css-level-1]
    patterns: ['tests/test_level1/**']

  - labels: [css-level-2]
    patterns: ['tests/test_level2/**']

  - labels: [css-level-3]
    patterns: ['tests/test_level3/**']

  - labels: [css-level-4]
    patterns: ['tests/test_level4/**']

  - labels: [css-level-5]
    patterns: ['tests/test_level5/**']

  - labels: [css-custom]
    patterns: ['tests/test_extra/**']

# Triage

triage_add: 'triage'
triage_skip: ['skip-triage']
triage_remove: ['confirmed']

# Review

review_add: 'needs-review'
review_skip: ['skip-review']
review_remove: ['approved']

# WIP

wip:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected
  - duplicate
  - invalid
  - triage
  - wontfix

# LGTM

lgtm_add:
  pull_request: [approved]
  issue: []

lgtm_remove:
  - work-in-progress
  - needs-review
  - needs-decision
  - needs-confirmation
  - requires-changes
  - rejected
  - duplicate
  - invalid
  - triage
  - wontfix

# Label Management

delete_labels: True

colors:
    bug: '#c45b46'
    feature: '#7b17d8'
    support: '#efbe62'
    maintenance: '#b2ffeb'
    category: '#709ad8'
    subcategory: '#bfd4f2'
    pending: '#f0f49a'
    rejected: '#f7c7be'
    approved: '#beed6d'
    low: '#dddddd'
    bot: '#000000'

labels:
- name: bug
  color: bug
  description: Bug report.

- name: feature
  color: feature
  description: Feature request.

- name: maintenance
  color: maintenance
  description: Maintenance chore.

- name: support
  color: support
  description: Support request.

- name: docs
  color: category
  description: Related to documentation.

- name: tests
  color: category
  description: Related to testing.

- name: infrastructure
  color: category
  description: Related to project infrastructure.

- name: source
  color: category
  description: Related to source code.

- name: selectors
  color: subcategory
  description: Related to selector implementations.

- name: css-parsing
  color: subcategory
  description: Related to CSS parsing.

- name: css-matching
  color: subcategory
  description: Related to CSS matching.

- name: API
  color: subcategory
  description: Related to the API.

- name: css-level-1
  color: subcategory
  description: CSS level 1 selectors.

- name: css-level-2
  color: subcategory
  description: CSS level 2 selectors.

- name: css-level-3
  color: subcategory
  description: CSS level 3 selectors.

- name: css-level-4
  color: subcategory
  description: CSS level 4 selectors.

- name: css-level-5
  color: subcategory
  description: CSS level 5 selectors.

- name: css-custom
  color: subcategory
  description: CSS custom selectors.

- name: more-info-needed
  color: pending
  description: More information is required.

- name: needs-confirmation
  color: pending
  description: The alleged behavior needs to be confirmed.

- name: needs-decision
  color: pending
  description: A decision needs to be made regarding request.

- name: confirmed
  color: approved
  description: Confirmed bug report or approved feature request.

- name: maybe
  color: low
  description: Pending approval of low priority request.

- name: duplicate
  color: rejected
  description: The issue has been previously reported.

- name: wontfix
  color: rejected
  description: The issue will not be fixed for the stated reasons.

- name: invalid
  color: rejected
  description: Invalid report (user error, upstream issue, etc).

- name: triage
  color: pending
  description: Issue needs triage.

- name: work-in-progress
  color: pending
  description: A partial solution. More changes will be coming.

- name: needs-review
  color: pending
  description: Needs to be reviewed and/or approved.

- name: requires-changes
  color: pending
  description: Awaiting updates after a review.

- name: approved
  color: approved
  description: The pull request is ready to be merged.

- name: rejected
  color: rejected
  description: The pull request is rejected for the stated reasons.

- name: skip-triage
  color: bot
  description: Tells bot to not tag a new issue with 'triage'.

- name: skip-review
  color: bot
  description: Tells bot to not tag a reviews with 'needs-review'.
