name: build

on:
  push:
    branches:
      - 'main'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, windows-latest]
        hatch-env: [py311, py312, py313, py314, stdlib]
        include:
          - hatch-env: py311
            python-version: '3.11'
            dev: dev
            continue-on-error: false
          - hatch-env: py312
            python-version: '3.12'
            dev: dev
            continue-on-error: false
          - hatch-env: py313
            python-version: '3.13'
            dev: dev
            continue-on-error: false
          - hatch-env: py314
            python-version: '3.14'
            dev: dev
            continue-on-error: false
          - hatch-env: stdlib
            python-version: '3.14'
            dev: dev-stdlib
            continue-on-error: false
        # exclude:
        #   - platform: windows-latest
        #     hatch-env: py314

    env:
      TOXENV: ${{ matrix.hatch-env }}

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools hatch
    - name: Types
      if: matrix.dev == 'dev'
      run: |
        hatch run +py=${{ matrix.python-version }} ${{ matrix.dev }}:types
    - name: Tests
      run: |
        hatch run +py=${{ matrix.python-version }} ${{ matrix.dev }}:tests
      continue-on-error: ${{ matrix.continue-on-error }}
    - name: Upload Results
      if: success()
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: ${{ matrix.platform }}-${{ matrix.hatch-env }}
        token: ${{ secrets.CODECOV_TOKEN }} # required
        fail_ci_if_error: false

  lint:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14]

    env:
      TOXENV: lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools hatch
    - name: Lint
      run: |
        python -m hatch run +py=${{ matrix.python-version }} dev:lint

  documents:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.14]

    env:
      TOXENV: documents

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools hatch
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Build documents
      run: |
        python -m hatch run docs:spellcheck
